# .streamlit/secrets.toml

[connections.mysql]
dialect = "mysql"
host = "rm-2ze51s440w5h4957mao.mysql.rds.aliyuncs.com"
port = 3306
database = "app_use"
username = "HDK1840"
password = "Hdk184018401840"
query = { charset = "utf8mb3_general_ci" }